// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxyrABNQzC2IwqLQEvuCc8kwk-h3LeVAI',
    appId: '1:62559891821:web:97a31d499c01a27ac6aa64',
    messagingSenderId: '62559891821',
    projectId: 'eventure-db',
    authDomain: 'eventure-db.firebaseapp.com',
    storageBucket: 'eventure-db.firebasestorage.app',
    measurementId: 'G-QTSY229H1F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2W1dwk_1QNBqRi0YxuszC7YRRBM1TfTE',
    appId: '1:62559891821:android:34ca22285d8fb265c6aa64',
    messagingSenderId: '62559891821',
    projectId: 'eventure-db',
    storageBucket: 'eventure-db.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAoVgMurQ66JVZQpVXlLlqOanedsnMzm2s',
    appId: '1:62559891821:ios:a4507948f0d80ba5c6aa64',
    messagingSenderId: '62559891821',
    projectId: 'eventure-db',
    storageBucket: 'eventure-db.firebasestorage.app',
    iosBundleId: 'com.example.eventure',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAoVgMurQ66JVZQpVXlLlqOanedsnMzm2s',
    appId: '1:62559891821:ios:a4507948f0d80ba5c6aa64',
    messagingSenderId: '62559891821',
    projectId: 'eventure-db',
    storageBucket: 'eventure-db.firebasestorage.app',
    iosBundleId: 'com.example.eventure',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBxyrABNQzC2IwqLQEvuCc8kwk-h3LeVAI',
    appId: '1:62559891821:web:9d1e798556e4fe6ac6aa64',
    messagingSenderId: '62559891821',
    projectId: 'eventure-db',
    authDomain: 'eventure-db.firebaseapp.com',
    storageBucket: 'eventure-db.firebasestorage.app',
    measurementId: 'G-LXPZF2DGR8',
  );
}
